### ISSUE TITLE
Adding black and white or greyscale color setting for the apps 

### ISSUE THREAD

**Issue by adarsh1109** [ottop/yam_launcher#17]
Adding black and white or greyscale color setting for the apps used within yam will be a useful feature for avoiding distraction within those apps

**Comment by ottop** [comment]
The launcher itself can be configured to only use black and white colours, but I can't do anything for apps. The function to turn your screen grayscale is built into Android (you can find it in accessibility or display settings depending on your device and there might even be a quick settings tile for it), so you can use that. 

While it is possible to enable grayscale through code, it requires the app user to enable a permission through adb that they shouldn't be enabling for an app like this in the first place. Considering the redundancy and security concerns, this won't be implemented.
