### ISSUE TITLE
new features for yam_launcher

### ISSUE THREAD

**Issue by lichingyun** [ottop/yam_launcher#21]
the development of mLauncher is finished, because the developer want to concentrate only in his project Easylauncher.
Can some of the features of mLauncher be used in yam_launcher?

**Comment by ottop** [comment]
What features are you interested in?

I can't directly use mLauncher code as that would require me to license YAM Launcher under GPL, which I do not wish to do. I can develop features myself when I shappen feel like it, though.

**Comment by lichingyun** [comment]
many thanks for your answer, I open some new tread to ask for new features 🙏
