### ISSUE TITLE
wrong entries when an app offers multiple app starters

### ISSUE THREAD

**Issue by mahibi** [ottop/yam_launcher#24]
Thank you for this app! It's the best minimalist open source launcher i found :+1: 

Only one minor thing that i found:

I use aCalendar+ which will create 2 app icons on my Samsung One UI launcher: one for aCalendar+ and one for aCalTasks+.
However in YAM launcher, there are two entries called aCalendar+ and both of them open the calendar view.

**Comment by alrajdev** [comment]
@ottop Apparently we are using App's name instead of Activity's label for the App menu list, so if an app has multiple Main Launcher activity like the above mentioned aCalendar+, the list is showing the app name for both instead of individual activity's label.

There are some changes we will have to make to solve the problem
* Use activity label instead of package name
* Use componentName (packageName + activityName) instead of packageName for everything (shortcut, hidden apps, app rename)

**Comment by ottop** [comment]
> @ottop Apparently we are using App's name instead of Activity's label for the App menu list, so if an app has multiple Main Launcher activity like the above mentioned aCalendar+, the list is showing the app name for both instead of individual activity's label.
> 
> There are some changes we will have to make to solve the problem
> 
> * Use activity label instead of package name
> * Use componentName (packageName + activityName) instead of packageName for everything (shortcut, hidden apps, app rename)

Certainly worth looking into. This change will break any existing preferences from everybody, though, so that will be annoying. Apart from that, I wouldn't expect too much trouble.

**Comment by alrajdev** [comment]
Also have to use ComponentName for app launch also, so it correctly opens the intended Activity

**Comment by alrajdev** [comment]
@ottop In the case of showing the menu we should show every Launchable activity with its label, but what about Hidden app? should we hide the whole app or only the selected Activity?

**Comment by ottop** [comment]
> @ottop In the case of showing the menu we should show every Launchable activity with its label, but what about Hidden app? should we hide the whole app or only the selected Activity?

Hiding should just hide the menu item that's hidden. Hiding a menu item and then having something else hide automatically would be bad UX.

**Comment by ottop** [comment]
I have now merged @alrajdev's fix to this to the main branch. There are a few more things I want to do for the next release and I'll probably make a release next week with this included.

**Comment by ottop** [comment]
1.7 has now been released with the fix included. It should, in theory, work now. If the issue persists after the update, let me know.
