### ISSUE TITLE
Digital detox features

### ISSUE THREAD

**Issue by mahibi** [ottop/yam_launcher#27]
While the launcher itself is great, I still find myself in opening my email, social media and RSS app too often without that I really want it.

It would be great to have some feature like
"Do you really want to open this app. If yes, for how long?" for selected apps.
When seeing this dialog, there could be some delay before being able to open the app.

Then there could also be a timer to ask/force to close the app after x minutes.

Iirc "minimalist phone: Screen time" combines these kind of features with the launcher quite nicely.
https://play.google.com/store/apps/details?id=com.qqlabs.minimalistlauncher

**Comment by ottop** [comment]
Thanks for the feedback!

However, controlling what the user can do with apps isn't within the scope of what I wish to implement. YAM Launcher is not intended as a full minimalism app suite, so its duty is merely as a launcher. There are third party options that are separate from any launcher for limiting how much apps can be used.

As for a dialog to double check launching an app, I can add that as an option.

**Comment by mahibi** [comment]
> However, controlling what the user can do with apps isn't within the scope of what I wish to implement. YAM Launcher is not intended as a full minimalism app suite, so its duty is merely as a launcher. 

Totally understandable!

> As for a dialog to double check launching an app, I can add that as an option.

That would be great

**Comment by ottop** [comment]
The confirmation dialogs are now out as an option in version 1.7.
