### ISSUE TITLE
Show "home screen" shortcuts?

### ISSUE THREAD

**Issue by wmburke** [ottop/yam_launcher#29]
I'm loving this launcher but can't figure out how to show Home Screen shortcuts like the kind that Firefox and Native Alpha create - in the apps list. These are Progressive Web Apps (PWAs), as described here: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/What_is_a_progressive_web_app

Is this currently possible, or on the roadmap?

Thank you!

**Comment by ottop** [comment]
These are currently not supported (as they are not accessed similarly to normal apps), but adding support for them is on the roadmap.

**Comment by wmburke** [comment]
Great news. Thank you!

**Comment by Hund** [comment]
Where can we find the roadmap? I'm also looking forward to this, and it would be fun to track the progress.

**Comment by thomasboom** [comment]
@rthery I'd at the very least be interested to take a look. If you want, you can open a PR at Codeberg. Because of reasons stated in our README, we don't support GitHub PR's anymore.
