### ISSUE TITLE
Shortcuts for most used apps/favorites.

### ISSUE THREAD

**Issue by newbee2011** [ottop/yam_launcher#3]
Hello.
New here. Tested the launcher today.
Thank you for your work and efforts.

 Asking for increase the number of shortcuts for most used apps/favorite apps. Used Olauncher Clutter Free before and it has up to 15 usuable shortcuts which I all used.

Thank you for taking note.

**Comment by ottop** [comment]
Thanks, I appreciate the feedback.

I'll look into the possibility of increasing the number of shortcuts for the next release. I can't guarantee that I will implement it, but at this point I imagine that it should be very simple to implement.

**Comment by newbee2011** [comment]
Thank you for your response.
Really fast. 🤙🏻

**Comment by ottop** [comment]
An update on this matter:

I hve implemented the additional shortcuts so they will be in the next release whenever that comes out. There will be the option to have up to 15 shortcuts and they automatically size themselves according to available space, so they can fit on mostly any phone screen.

**Comment by newbee2011** [comment]
Awesome. Thank you very much. 👍🏻🤙🏻

**Comment by ottop** [comment]
1.1 is now out and this should be implemented alongside the date gesture and a bunch of other customization changes and other improvements. Let me know if you run into any issues once you have the update.
