### ISSUE TITLE
Shortcut to calendar tapping on date.

### ISSUE THREAD

**Issue by newbee2011** [ottop/yam_launcher#4]
Hello......again.

Mentioned that there is no shortcut to the calendar app when tapping on the date at the homescreen like the shortcut to the alarm/clock app when tapping on the clock.

Thank you.

**Comment by ottop** [comment]
Thanks,

I'll look into it for the next release.

**Comment by newbee2011** [comment]
Great. Thank you very much.🤙🏻

**Comment by ottop** [comment]
This one is now implemented as well. Will be in the next release.

**Comment by ottop** [comment]
1.1 is now out with this feature. I'll close the issue for now as there shouldn't be much room for issues with the implementation.
