### ISSUE TITLE
Spacing between items in app list

### ISSUE THREAD

**Issue by jacksongoode** [ottop/yam_launcher#5]
It would be nice if there was a way to configure the vertical spacing between the items within the app list.

**Comment by ottop** [comment]
Thanks for the feedback. I'll look into it and see if I can implement something for the next release.

**Comment by ottop** [comment]
An update for this:

I have implemented customization options for spacing for the app menu and the home screen shortcuts. These will be in the next release whenever it comes out.

**Comment by jacksongoode** [comment]
Awesome thank you!

**Comment by ottop** [comment]
1.1 with the configurable item space has now been released (I managed to implement a lot of stuff today). Let me know if you run into any problems once you have the update.

**Comment by jacksongoode** [comment]
Sounds good thanks!
