### ISSUE TITLE
Add Compatibility for Older Versions of Android

### ISSUE THREAD

**Issue by MilesBHuff** [ottop/yam_launcher#7]
Hi!  This launcher looks great, and it sounds like it would be perfect for e-ink e-readers.
Unfortunately, most Android-based e-readers run old versions of Android.
Is there any chance you might please consider adding support for older versions of Android?
I know most BOOX devices run Android 11 or earlier, and the latest B&N Nook devices still run Android 8 (wtf...).  I'm on one of those Nooks, myself.  There isn't really any launcher in F-Droid that seems to fit the needs of this device better than yours.
Thank you for your time in reading this request.

**Comment by ottop** [comment]
Hi,

Thank you for the feedback and I can see the use case. 

However, adding in older versions, especially if I build support for versions as old as Android 8, would very likely require me to run different code depending on the Android version of the device. I'll play around with it and see if it just works, but if it needs additional work, I won't implement it as it would add in too much work for testing.

**Comment by MilesBHuff** [comment]
Thank you, @ottop!  That sounds very reasonable -- thank you so much for looking into this!

**Comment by ottop** [comment]
I have looked at it quite a bit and it looks like it would require significant modification. All kinds of methods would need to be modified to also support older versions and it would be a burden. As such, I'm afraid that I won't lower the minimum supported version.

**Comment by MilesBHuff** [comment]
Sad.  Thank you for at least looking into it!
